# Branch-Pruner | GitHub Action Workflow
# 
# Description: Truncates a branch's old commit history
# Author: Sitdisch
# Source: https://github.com/myactionway/branch-pruner-workflow
# License: MIT
# Copyright (c) 2021 Sitdisch
# 
# CAUTION: IT IS A POWERFUL TOOL AND YOU USE IT AT YOUR OWN RISK. CUTS CAN'T BE UNDONE.

name: 'Branch-Pruner'

########################################################################
# DEFINE YOUR TOKEN, INPUTS AND TRIGGERS IN THE FOLLOWING
########################################################################

# TOKEN and INPUTS as environmental variables
env:
  # Token for all triggers (INSERT ONLY THE NAME NEVER THE REAL VALUE)
  TOKEN: #  insert ${{ secrets.<TOKEN_NAME> }} and replace <TOKEN_NAME>
  # 
  # Inputs for not manually triggered workflows (if empty, defaults are used)
  NEW-FIRST-COMMIT: # e.g. commit-hash or HEAD~N etc.
  REPOSITORY: # target repository e.g. 'dummy/mytargetrepo'
  BRANCH: # branch to be pruned e.g 'master'
  USER-NAME: # user who should commit e.g. 'dummy'
  USER-EMAIL: # e.g. 'dummy@gmail.com'
  # 
  # YOU DON'T HAVE TO DEFINE ANYTHING FOR THE DEFAULT VALUES
  DEFAULT-REPOSITORY: ${{ github.repository }} # repo with this file
  DEFAULT-BRANCH: 'master'
  DEFAULT-USER-NAME: 'github-actions[bot]'
  DEFAULT-USER-EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'

# TRIGGERS
on:
  # push:
  # schedule: # Check your schedule here => https://crontab.guru/
  #   - cron: '00 23 28 * *' # e.g. every 28th day of a month at 23:00
  # 
  # YOU DON'T HAVE TO DEFINE ANYTHING FOR THE WORKFLOW_DISPATCH HERE
  workflow_dispatch:
    inputs:
      new-first-commit:
        description: 'New first commit'
        required: true
      repository:
        description: 'Target repository'
        required: true
      branch:
        description: 'Branch to be pruned'
        required: true
        default: 'master'
      user-name:
        description: 'User who should commit'
        required: true
        default: 'github-actions[bot]'
      user-email:
        description: 'User e-mail address'
        required: true
        default: '41898282+github-actions[bot]@users.noreply.github.com'

########################################################################
# YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
########################################################################

# Jobs
jobs:
  branch-pruner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository || env.REPOSITORY || env.DEFAULT-REPOSITORY }}
          token: ${{ env.TOKEN }}
          fetch-depth: '0'
          ref: ${{ github.event.inputs.branch || env.BRANCH || env.DEFAULT-BRANCH }}
      - uses: myactionway/branch-pruner-action@v1.0
        with:
          new-first-commit: ${{ github.event.inputs.new-first-commit || env.NEW-FIRST-COMMIT }}
          branch: ${{ github.event.inputs.branch || env.BRANCH || env.DEFAULT-BRANCH }}
          user-name: ${{ github.event.inputs.user-name || env.USER-NAME || env.DEFAULT-USER-NAME }}
          user-email: ${{ github.event.inputs.user-email || env.USER-EMAIL || env.DEFAULT-USER-EMAIL }}
