# Lighthouse-Badger-Advanced | GitHub Action Workflow
# 
# Description: Generates, adds & updates manually/automatically Lighthouse badges & reports form one/multiple input URL-group(s) to one/multiple target repo(s)/branch(es)
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-badger-workflows
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse-Badger-Advanced'

########################################################################
# DEFINE YOUR DEFAULTS (INPUTS & TRIGGERS) IN THE FOLLOWING
########################################################################

# INPUTS as environmental variables (env)
env:
  TOKEN: 'YOUR_TOKEN' # target token; insert only the name never the real value e.g. 'YOUR_TOKEN'
  # To change predefined values, just override them
  REPO-BRANCH: '${{ github.repository }} master' # target repository (predefined: repo with this file) and target branch
  USER-NAME: 'github-actions[bot]' # user who should commit
  USER-EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  COMMIT-MESSAGE: 'Lighthouse-Badger[bot]: Results Added'
  RESULTS-TYPE: 'both' # 'mobile', 'desktop', 'both' or 'both_p'
  MOBILE-LIGHTHOUSE-PARAMS: '--throttling.cpuSlowdownMultiplier=2' # Lighthouse parameters mobile audit
  DESKTOP-LIGHTHOUSE-PARAMS: '--preset=desktop --throttling.cpuSlowdownMultiplier=1' # Lighthouse parameters desktop audit

# TRIGGERS
on:
  # page_build:
  # schedule: # Check your schedule here => https://crontab.guru/
  #   - cron: '55 23 * * 0' # e.g. every Sunday at 23:55
  workflow_dispatch:
    # No predefined inputs; The environmental variables defined in this file are used instead when this trigger is triggered.

########################################################################
# YOU CAN JUMP TO THE FIRST URL-GROUP DEFINITION BELOW
########################################################################

# Jobs
jobs:
  lighthouse-badger-advanced:
    name: ${{ matrix.NAME }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          ##############################################################
          # FIRST URL-GROUP | DEFINE YOUR ENV IN THE FOLLOWING
          ##############################################################
          - NAME: 'URL-GROUP 1'
            URLS: 'https://github.com/sitdisch https://github.com/mythemeway'
            BADGES-ARGS: '-b pagespeed -o lighthouse_results/first_group -r'
            COMMIT-MESSAGE: 'Lighthouse-Badger[bot]: Results Added | First URL-Group'
            # Your defaults will be used unless you redefine the following env
            # TOKEN: # insert only the name never the real value
            # REPO-BRANCH:
            # RESULTS-TYPE:
            # MOBILE-LIGHTHOUSE-PARAMS:
            # DESKTOP-LIGHTHOUSE-PARAMS:
            # USER-NAME:
            # USER-EMAIL:
          ##############################################################
          # SECOND URL-GROUP | DEFINE YOUR ENV IN THE FOLLOWING
          ##############################################################
          - NAME: 'URL-GROUP 2'
            URLS: 'https://mythemeway.github.io/Dark-Particle/ https://mythemeway.github.io/Dark-Particle/projects/2020/10/31/project-1.html'
            BADGES-ARGS: '-b flat -o lighthouse_results/second_group -r'
            COMMIT-MESSAGE: 'Lighthouse-Badger[bot]: Results Added | Second URL-Group'
            # Your defaults will be used unless you redefine the following env
            # TOKEN: # insert only the name never the real value
            REPO-BRANCH: 'mytestdummy/test master'
            # RESULTS-TYPE:
            # MOBILE-LIGHTHOUSE-PARAMS:
            # DESKTOP-LIGHTHOUSE-PARAMS:
            # USER-NAME:
            # USER-EMAIL:
          ##############################################################
          # THIRD URL-GROUP | FEEL FREE TO ADD MORE URL-GROUPS LIKE ABOVE
          ##############################################################
          # 
          # ...
          # 
    ####################################################################
    # THAT'S IT; YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
    ####################################################################
    steps:
      - name: Preparatory Tasks
        run: |
          REPOSITORY=`expr "${{ env.REPO-BRANCH }}" : "\([^ ]*\)"`
          BRANCH=`expr "${{ env.REPO-BRANCH }}" : ".* \([^ ]*\)"`
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        env:
          REPO-BRANCH: ${{ matrix.REPO-BRANCH || env.REPO-BRANCH }}
      - uses: actions/checkout@v2.3.4
        with:
          repository: ${{ env.REPOSITORY }}
          token: ${{ secrets[matrix.TOKEN] || secrets[env.TOKEN] }}
          ref: ${{ env.BRANCH }}
      - uses: actions/checkout@v2.3.4
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested
      - uses: mytestdummy/testaction@master
        with:
          urls: ${{ matrix.URLS }}
          badges-args: ${{ matrix.BADGES-ARGS || env.BADGES-ARGS }}
          results-type: ${{ matrix.RESULTS-TYPE || env.RESULTS-TYPE }}
          mobile-lighthouse-params: ${{ matrix.MOBILE-LIGHTHOUSE-PARAMS || env.MOBILE-LIGHTHOUSE-PARAMS }}
          desktop-lighthouse-params: ${{ matrix.DESKTOP-LIGHTHOUSE-PARAMS || env.DESKTOP-LIGHTHOUSE-PARAMS }}
          user-name: ${{ matrix.USER-NAME || env.USER-NAME }}
          user-email: ${{ matrix.USER-EMAIL || env.USER-EMAIL }}
          commit-message: ${{ matrix.COMMIT-MESSAGE || env.COMMIT-MESSAGE }}
