name: Manually triggered workflow

# 
# DEFINE YOUR INPUTS FOR NO MANUAL DISPATCH WORKFLOWS HERE
# 
env:
  NEW-FIRST-COMMIT-NOMANUAL: HEAD~17 # e.g. HEAD~20
  BRANCH-NOMANUAL: test # e.g. master
  USER-NAME-NOMANUAL: github-actions[bot]
  USER-EMAIL-NOMANUAL: 41898282+github-actions[bot]@users.noreply.github.com
  
# 
# DEFINE YOUR WORKFLOW TRIGGERS HERE
# 
on:
  # push:
  # schedule:
  #   - cron: '30 23 * * *' # e.g. every 28th day of a month at 23:00
  # 
  # YOU DON'T HAVE TO DEFINE ANYTHING FOR THE WORKFLOW_DISPATCH HERE
  # 
  workflow_dispatch:
    inputs:
      new-first-commit:
        description: 'New first commit'
        required: true
      branch:
        description: 'Branch to be pruned'
        required: true
        default: 'master'
      user-name:
        description: 'User who should commit'
        required: true
        default: 'github-actions[bot]'
      user-email:
        description: 'User e-mail address'
        required: true
        default: '41898282+github-actions[bot]@users.noreply.github.com'

# 
# YOU DON'T HAVE TO DEFINE ANYTHING HERE ;)
# 
jobs:
  commits-cutting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.YOUR_TOKEN }}
          fetch-depth: '0'
          ref: ${{ github.event.inputs.branch || env.BRANCH-NOMANUAL }}
      - uses: mytestdummy/testaction@master
        with:
          new-first-commit: ${{ github.event.inputs.new-first-commit || env.NEW-FIRST-COMMIT-NOMANUAL }}
          branch: ${{ github.event.inputs.branch || env.BRANCH-NOMANUAL }}
          user-name: ${{ github.event.inputs.user-name || env.USER-NAME-NOMANUAL }}
          user-email: ${{ github.event.inputs.user-email || env.USER-EMAIL-NOMANUAL }}
