name: Manually triggered workflow

# DEFINE YOUR INPUTS FOR NO DISPATCH WORKFLOWS HERE
env:
  NEW-FIRST-COMMIT: HEAD~12 # e.g. HEAD~20
  BRANCH: master # e.g. master
  
# DEFINE YOUR WORKFLOW TRIGGERS HERE
on:
  schedule:
    - cron: '00 13 * * *' # e.g. every 28th day of a month at 23:00
  # YOU DON'T HAVE TO DEFINE ANYTHING FOR THE WORKFLOW_DISPATCH HERE
  workflow_dispatch:
    inputs:
      new-first-commit:
        description: 'New first commit'
        required: true
      branch:
        description: 'Branch to be pruned'
        required: true
        default: 'master'

# YOU DON'T HAVE TO DEFINE ANYTHING HERE ;)
jobs:
  manual_cutting:
    if: ${{ github.event.inputs.new-first-commit }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.YOUR_TOKEN }}
          fetch-depth: '0'
          ref: ${{ github.event.inputs.branch }}
      - uses: mytestdummy/testaction@master
        with:
          new-first-commit: ${{ github.event.inputs.new-first-commit }}
          branch: ${{ github.event.inputs.branch }}
  no_manual_cutting:
    if: ${{ github.event.inputs.new-first-commit }} == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.YOUR_TOKEN }}
          fetch-depth: '0'
          ref: ${{ env.BRANCH }}
      - uses: mytestdummy/testaction@master
        with:
          new-first-commit: ${{ env.NEW-FIRST-COMMIT }}
          branch: ${{ env.BRANCH }}
